server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_apis
    username: root
    password: shuaib

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#  security:
#    user:
#      name: shuaib
#      password: shuaib
#      roles:
#        ADMIN

project:
  image: images/
#
#login:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#

